dist: xenial
language: python
python:
  - "3.7"

cache:
  - pip
  - ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - python3-dev
      - g++-7

env:
  global:
    - CC=gcc-7
    - CXX=g++-7
  matrix:
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=5.0.0
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=5.0.0
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.1.0 CHAINER_VERSION=5.0.0
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.1.0 CHAINER_VERSION=5.0.0
    # torch nightly with chainer stable
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=nightly CHAINER_VERSION=5.0.0
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=nightly CHAINER_VERSION=5.0.0
    # chainer nightly with torch stable
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=6.0.0
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=6.0.0

matrix:
  allow_failures:
    # torch nightly with chainer stable
    - python: 3.7
      env: USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=nightly CHAINER_VERSION=5.0.0
    - python: 3.7
      env: USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=nightly CHAINER_VERSION=5.0.0
    # chainer nightly with torch stable
    - python: 3.7
      env: USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=6.0.0
    - python: 3.7 
      env: USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=6.0.0

install:
  - ./ci/install.sh


script:
  - ./ci/test_shell.sh
  - ./ci/test_python.sh
  - |
    if $USE_CONDA; then
      source tools/venv/bin/activate
    fi
    travis-sphinx build --source=doc --nowarn

sudo: false

after_success:
    - travis-sphinx deploy
