dist: xenial
language: python
python:
  - "3.7"

cache:
  - pip
  - ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - python3-dev
      - g++-7

env:
  global:
    - CC=gcc-7
    - CXX=g++-7
  matrix:
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=5.0.0
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=5.0.0
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.1.0 CHAINER_VERSION=5.0.0
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.1.0 CHAINER_VERSION=5.0.0
    # torch nightly with chainer stable
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=nightly CHAINER_VERSION=5.0.0
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=nightly CHAINER_VERSION=5.0.0
    # chainer nightly with torch stable
    - USE_CONDA=false ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=6.0.0
    - USE_CONDA=true ESPNET_PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CHAINER_VERSION=6.0.0

install:
  - pip install chainer==${CHAINER_VERSION};
  - |
    if [[ ${USE_CONDA} == false ]]; then
        if [[ ${TH_VERSION} == nightly ]]; then
            pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        else
            pip install --quiet torch==${TH_VERSION} -f https://download.pytorch.org/whl/cpu/stable
        fi
    else
        cd tools
        make PYTHON_VERSION=${ESPNET_PYTHON_VERSION} venv
        source venv/etc/profile.d/conda.sh
        conda config --set always_yes yes --set changeps1 no
        conda activate
        conda update -y conda
        if [[ ${TH_VERSION} == nightly ]]; then
            conda install pytorch-nightly-cpu -c pytorch
        else
            conda install -y pytorch-cpu=${TH_VERSION} -c pytorch
        fi
        cd -
    fi
  - ./ci/install.sh

script:
  - ./ci/test_shell.sh
  - ./ci/test_python.sh
  - travis-sphinx build --source=doc --nowarn

sudo: false

after_success:
    - travis-sphinx deploy
