# network architecture
# encoder related
encoder: rnn
encoder_conf:
    rnn_type: lstm
    bidirectional: True
    use_projection: True
    num_layers: 4
    hidden_size: 320
    output_size: 320
    dropout: 0.0
    subsample: "1_2_2_1_1"  # skip every n frame from input to nth layers
# decoder related
decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 300
    sampling_probability: 0.0   # scheduled sampling option
    dropout: 0.0
    context_residual: False
    replace_sos: False
    num_encs: 1

# hybrid CTC/attention
e2e_conf:
    ctc_weight: 0.5
    lsm_weight: 0.0     # label smoothing option

# minibatch related
batch_size: 30

# optimization related
init: chainer
max_epoch: 20
optim: adadelta
optim_conf:
    lr: 1.0
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0
patience: 3
val_scheduler_criterion:
- eval
- loss
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
