# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04
        environment:
          ESPNET_PYTHON_VERSION: 3.7
          TH_VERSION: 1.1.0
          CHAINER_VERSION: 5.0.0
          USE_CONDA: true
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get install -y cmake g++-7
            ./ci/install.sh

      - run:
          name: run tests
          command: |
            ./ci/test_shell.sh
            ./ci/test_python.sh
