# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: conda/miniconda3:latest
        environment:
          ESPNET_PYTHON_VERSION: 3.7
          TH_VERSION: 1.1.0
          CHAINER_VERSION: 5.0.0
          USE_CONDA: false
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            cd tools
            conda create --prefix venv python=${ESPNET_PYTHON_VERSION}
            source venv/etc/profile.d/conda.sh
            conda config --set always_yes yes --set changeps1 no
            conda activate
            conda update -y conda
            if [[ ${TH_VERSION} == nightly ]]; then
                conda install pytorch-nightly-cpu -c pytorch
            else
                conda install -y pytorch-cpu=${TH_VERSION} -c pytorch
            fi
            cd -
            pip install chainer==${CHAINER_VERSION}
            ./ci/install.sh

      - run:
          name: run tests
          command: |
            source tools/venv/bin/activate
            ./ci/test_shell.sh
            ./ci/test_python.sh
