# general
optim: adadelta
optim_conf:
    lr: 1.0
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0
init: xavier_uniform
batch_type: folded
batch_size: 30
max_epoch: 15
patience: 3

# criterion
val_scheduler_criterion:
    - valid
    - loss
early_stopping_criterion:
    - valid
    - loss
    - min
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1

# network
encoder: rnn
encoder_conf:
    rnn_type: lstm
    bidirectional: True
    use_projection: True
    num_layers: 4
    hidden_size: 320
    output_size: 320
decoder: rnn
transducer_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 300
    joint_space_size: 300
    dropout: 0.1
    dropout_embedding: 0.1
    use_attention: True
    att_conf:
        atype: location
        adim: 320
        aconv_chans: 10
        aconv_filts: 100