# network architecture
# encoder related
ecnoder: rnn
encoder_conf:
    rnn_type: lstm
    bidirectional: True
    use_projection: True
    num_layers: 6
    hidden_size: 320
    output_size: 320
# decoder related
decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 300
    sampling_probability: 0.0
    att_conf:
        aheads: 4
        atype: location
        awin: 5
        adim: 320
        aconv_chans: 10
        aconv_filts: 100


# hybrid CTC/attention
e2e_conf:
    ctc_weight: 1.0
    lsm_weight: 0.05


# minibatch related
batch_size: 30
max_length:
    - 800
    - 150

# optimization related
optim: adadelta
max_epoch: 15
patience: 3

