# network architecture
# encoder related
etype: blstm     # encoder architecture type
elayers: 2
eunits: 1024
eprojs: 1024
subsample: "1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 2
dunits: 1024
context-residual: true
# attention related
atype: add
adim: 1024

# minibatch related
batch-size: 32
maxlen-in: 100  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 100 # if output length > maxlen_out, batchsize is automatically reduced

# other config
dropout-rate: 0.2
lsm_weight: 0.1
dropout_rate: 0.3
dropout_rate_decoder: 0.3
weight_decay: 1e-6

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 20
patience: 3

# scheduled sampling option
sampling-probability: 0.0

# pre-training related
asr_model: ''
mt_model: ''
